NAME = do-op
CC = cc
CFLAGS = -Wall -Wextra -Werror
SRCS = main.c atoi.c utils.c functions.c
OBJS = $(SRCS:.c=.o)

all : $(NAME)
%.o : %.c 
	$(CC) $(CFLAGS) -c $< -o $@
$(NAME) : $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(NAME)
clean :
	rm -f $(OBJS)
fclean : clean
	rm -f $(NAME)
re : fclean all
